

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>ログイン完了</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
      <link rel ="stylesheet" type="text/css" href="views/style.css">
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <h1 class="text-center mt-5">ログイン完了</h1>
          <p class="text-center">ようこそ！<strong><?php echo $_SESSION['email']; ?></strong>さん!</p>
          <p class="text-center">このサイトを利用するためにはまずはじめに、プログラミング経験についてのアンケートに回答していただく必要があります．<br>下記の回答ボタンからアンケートをお答えください．</p>
          <form method="POST" action="index.php?event=StartSuvey" class="text-center">
            <button type="submit" class="btn btn-primary">アンケートに回答</button>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

<!--
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>ログイン完了</title>
    <style>
      strong {
      font-weight: bold;
      }
    </style>
  </head>
  <body>
    <center>
      <h1>会員登録</h1><br>
      ようこそ！<strong><?echo $_SESSION['email'];?></strong>さん!
      <p>このサイトを利用するためにはまずはじめに,プログラミング経験についてのアンケート
	に回答していただく必要があります．<br>下記の回答ボタンからアンケートをお答えください．
      </p>
     <form method="POST" action="index.php?event=login">
	  <input type="submit" value="アンケートに回答">
	</form>

  </body>

</html>

!-->
