<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>会員登録完了</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
     <link rel ="stylesheet" type="text/css" href="views/style.css">
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <h1 class="text-center mt-5">会員登録完了</h1>
          <p class="text-center">会員登録が完了しました！ログインページに戻りご登録していただいた情報を入力し、ログインしてください。</p>
          <form method="POST" action="index.php?event=login" class="text-center">
            <button type="submit" class="btn btn-primary">ログインページへ</button>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>


<!--
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>会員登録完了</title>
  </head>
  <body>
    <center>
      <h1>会員登録</h1><br>
      会員登録が完了しました！
      ログインページに戻りご登録していてだいた情報を入力し，ログインしてください
      <form method="POST" action="index.php?event=login">
	  <input type="submit" value="ログインページへ">
	</form>

  </body>

</html>

-->
