<?php
if(isset($view['code'])){
    switch($view['code']){
        case 'NoEnterEmail':
            $ErrorCode =  'メールアドレスを入力してください';
            break;
        case 'NoEnterPassword':
            $ErrorCode =  '登録パスワードを入力してください';
            break;
        case 'DifferentPassword':
            $ErrorCode =  'パスワードが一致しません';
            break;
        case 'AlreadyRegstrationEmail':
            $ErrorCode =  'このメールアドレスはすでに使用されています.';
            break;
        default:
            $ErrorCode = '予期せぬエラーです';
    }
}
?>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>会員登録</title>
  </head>
  <body>
    <center>
      <h1>会員登録</h1><br>
      登録するメールアドレスとパスワードをご入力ください<br>
    <?php echo '<span style="color: red;">' . htmlspecialchars($ErrorCode) . '</span>'; ?>
      <form method="POST" action="index.php?event=ReceiveRegstration">
	メールアドレス<input type="text" name="email"><br>
	パスワード<input type="password" name="password"><br>
	確認のため，パスワードをもう言う一度ご入力ください
	<input type="password" name="password2"><br>
	<input type="submit" value="登録"><br><br>
      </form>

      <form method="POST" action="index.php?event=login">
            <input type="submit" value="ログインページに戻る">
    </form>
  </body>

</html>
